= Von der Freiheit der Denkenden Menschen (Arbeitstitel)

== Intro
Wenn Menschen über das Denken nachdenken führt das oft zu Frustration. Das Denken wird verstanden als ein mentaler, innerer, privater Vorgang, das durch eine unüberbrückbare Kluft von seinem Gegenstand getrennt ist. Unsere Vorstellungen, so gut sie auch begründet sein mögen, werden möglicherweise der Realität, wie sie wirklich, an sich ist nicht gerecht, zumindest könne es keine Garantie dafür geben, daß sie mit der Wirklichkeit übereinstimmen. Den denkenden Menschen kann dieses Szenario nicht zufrieden stellen. Menschen, die über das Denken nicht nachdenken, erleben diese Frustration nicht. Unglücklicherweise kann diese Frustration dann umgekehrt auch oft dazu führen, daß Menschen aufhören über das Denken nachzudenken. Wie ich in diesem Aufsatz zeigen will beraubt ein fehlendes Verständnis dafür, was es heißt zu denken, zu argumentieren, zu rechtfertigen, nach der Wahrheit, dem Schönen und dem Guten zu suchen, die Menschen auch einer positiven Kraft, die Zukunft kreativ zu gestalten. Wenn wir dagegen verstehen, daß unser Wissen ein gemeinschaftliches Schaffen ist, das zu keinem Zeitpunkt abgeschlossen ist, und keineswegs einer absoluten Realität gerecht werden muß, können wir uns in aller Ruhe daran machen, aus unserer Erfahrung die Zukunft zu bauen.
Diejenigen, die sich mit philosophischer Literatur beschäftigen werden erkennen, daß diese Überlegungen viele Anregungen Ludwig Wittgenstein und Richard Rorty verdanken. Womöglich gibt es zu dem, was diese beiden Denken geschrieben haben, auch nichts wirklich Neues hinzuzufügen. Ich begegne aber tagtäglich so vielen Verirrungen, die, wie ich in jeweils einem Kapitel über das sogenannte "jüngste Gericht" und die Menschenrechte zeigen will, durchaus gesamtgesellschaftlich schädlich sind, so daß es vielleicht der Mühe wert ist diese Gedanken und ihren befreienden Charakter hier nochmals auszuführen.

== Wahrheit und Existenz

=== Wahrheit als Korrespondenz

=== Was es gibt

=== Andere philosophische Wahrheitstheorien

=== Horizontale und vertikale Rechtfertigungen

==== Ein Beispiel aus der Mathematik

== Das jüngste Gericht

== Menschenrechte

== Ausblick

=== Vom Fortsetzen einer (Spiel-) Regel