= Von der Freiheit der Denkenden Menschen (Arbeitstitel)

== Intro
Wenn Menschen über das Denken nachdenken führt das oft zu Frustration. Das Denken wird verstanden als ein mentaler, innerer, privater Vorgang, das durch eine unüberbrückbare Kluft von seinem Gegenstand getrennt ist. Unsere Vorstellungen, so gut sie auch begründet sein mögen, werden möglicherweise der Realität, wie sie wirklich, an sich ist nicht gerecht, zumindest könne es keine Garantie dafür geben, daß sie mit der Wirklichkeit übereinstimmen. Den denkenden Menschen kann dieses Szenario nicht zufrieden stellen. Menschen, die über das Denken nicht nachdenken, erleben diese Frustration nicht. Unglücklicherweise kann diese Frustration dann umgekehrt auch oft dazu führen, daß Menschen aufhören über das Denken nachzudenken. Wie ich in diesem Aufsatz zeigen will beraubt ein fehlendes Verständnis dafür, was es heißt zu denken, zu argumentieren, zu rechtfertigen, nach der Wahrheit, dem Schönen und dem Guten zu suchen, die Menschen auch einer positiven Kraft, die Zukunft kreativ zu gestalten. Wenn wir dagegen verstehen, daß unser Wissen ein gemeinschaftliches Schaffen ist, das zu keinem Zeitpunkt abgeschlossen ist, und keineswegs einer absoluten Realität gerecht werden muß, können wir uns in aller Ruhe daran machen, aus unserer Erfahrung die Zukunft zu bauen.
Diejenigen, die sich mit philosophischer Literatur beschäftigen werden erkennen, daß diese Überlegungen viele Anregungen Ludwig Wittgenstein und Richard Rorty verdanken. Womöglich gibt es zu dem, was diese beiden Denken geschrieben haben, auch nichts wirklich Neues hinzuzufügen. Ich begegne aber tagtäglich so vielen Verirrungen, die, wie ich in jeweils einem Kapitel über das sogenannte "jüngste Gericht" und die Menschenrechte zeigen will, durchaus gesamtgesellschaftlich schädlich sind, so daß es vielleicht der Mühe wert ist diese Gedanken und ihren befreienden Charakter hier nochmals auszuführen.

== Wahrheit und Existenz

=== Wahrheit als Korrespondenz

=== Was es gibt

=== Andere philosophische Wahrheitstheorien

==== Kohärenztheorie

==== Pragmatischtische Theorie der Wahrheit

=== Horizontale und vertikale Begründungen
Philosophische Theorien der Wahrheit, egal welchen Typs, zeichnen sich dadurch aus, daß sie zusätzlich zu den gewöhnlichenn, argumentativen Rechtfertigungen einzelner Behauptungen eine Natur der Wahrheit postulieren, irgendetwas was dafür verantwortlich ist, daß etwas wirklich wahr ist oder nicht, egal zu welchem Ergenbnis wir mit unseren argumentativen Verfahren wir kommen. Ich will diese außer-argumentativen Ideen, wodurch etwas wahr, gut oder schön wird, vertikale Begründungen nennen. Unsere Meinungen über die Welt müssen sich einer absoluten, nicht menschen-abhängigen Natur der Wahrheit beugen. Diese Natur steht sozusagen im "rechten Winkel" zu unseren in der menschlichen Gesellschaft anerkannten Begründungen. Die philosophsiche Wahrheit und die argumentative Wahrheit sind unabhängige Vektoren. Die philosophische  Wahrheit zeigt auf etwas "außerhalb" unseres Netzes sozial argumentativer, gut begründeter Meinungen, die unsere Kriterien gut gerechtfertigten Wissens erfüllen. Sei es die Welt an sich, sei es ein abstrakter Begriff der Kohärenz, sei es die absolute Gültigkeit des Nützlichen für eine bessere Zukunft der Menschheit.
Wenn man diese absolute, unhintergehbare Natur der Wahrheit fallen läßt, und die letzte und einzige Begründung unseres vorgeblichen Wissens bei uns Menschen und ihrer Praxis beläst, die in ihre Argumentationsmuster, den sprachlichen und außersprachlichen Kontext miteinbeziehen, dann kann man durchaus sagen, daß ein Gedanke wahr ist, wenn er mit der Realität übereinstimmt, oder wenn er zu unseren anderen gut begründeten Gedanken paßt, oder daß wir in der Regel denjenigen Meinungen den Vorzug geben, die uns in unserer Lebenspraxis helfen und idealerweise zu einem größeren Glück der größeren Zahl führen. Wir müssen also aus den aufgeblasenen, philosophischen Theorien die Luft raus lassen, indem wir sie nicht als vertikale Beschreibungen einer außer-pragmatischen Natur der Wahrheit betrachten, sondern als bloß weitere Kommentare zu unserem System von Meinungen, die aber selbst jederzeit hinterfragbar und einer Begründung erforderlich sein können. Diese Kommentare sind "horizontal", sie gehören zu unserem Netz von Meinungen einfach dazu. 

=== Beispiele

==== Ist die Kontinuumshypothese wahr?

==== Gibt es die Teilchen der Physik wirklich?

==== Gibt es historische Wahrheiten?

== Das jüngste Gericht

== Menschenrechte

== Droht uns der Relativismus, wenn wir das Absolute aufgeben?

== Ausblick

=== Vom Fortsetzen einer (Spiel-) Regel