= Von der Freiheit der Denkenden Menschen (Arbeitstitel)

== Intro
Wenn Menschen über das Denken nachdenken, endet das oft in Frustration, weil die Objekte des Denkens sich diesem zwangsläufig zu entziehen scheinen. Das Denken wird dann verstanden als ein mentaler, innerer, privater Vorgang, der durch eine unüberbrückbare Kluft von seinem Gegenstand getrennt sei. Unsere Vorstellungen, so gut sie auch begründet sein mögen, würden der Realität, wie sie wirklich, an sich ist, nicht gerecht, zumindest könne es keine Garantie dafür geben, dass diese mit der Wirklichkeit übereinstimmen.

Den denkenden Menschen kann das nicht zufrieden stellen. Dagegen erleben Menschen, die über das Denken nicht nachdenken, diese Verzweiflung nicht, weil im alltäglichen Leben die vermeintliche Kluft zwischen Denken und Wirklichkeit niemals zum Problem wird. Wäre es also das Beste aufzuhören, über das Denken nachzudenken? Keineswegs! Wie ich in diesem Aufsatz zeigen will beraubt ein philosophisch irregeleitetes Verständnis davon, was es heißt zu denken, zu argumentieren, zu rechtfertigen, nach der Wahrheit, dem Schönen und dem Guten zu suchen, die Menschen einer positiven Kraft, die Zukunft kreativ zu gestalten. Wenn wir dagegen verstehen, dass es bei den Resultaten des Denkens, also den Gedanken oder im optimalen Fall dem Wissen ein gemeinschaftliches Schaffen ist, das zu keinem Zeitpunkt endgültig und abgeschlossen ist, und keineswegs einer absoluten Realität gerecht werden muss, können wir unbeschwert und frei, das Denken für eine bessere Welt einsetzen.


Diejenigen, die sich mit philosophischer Literatur beschäftigen werden erkennen, dass diese Überlegungen viele Anregungen Ludwig Wittgenstein und Richard Rorty verdanken. Womöglich gibt es zu dem, was diese beiden Denken geschrieben haben, auch nichts wirklich Neues hinzuzufügen. Ich begegne aber tagtäglich so vielen Verirrungen, die, wie ich in jeweils einem Kapitel über das sogenannte "jüngste Gericht" und die Menschenrechte zeigen will, durchaus gesamtgesellschaftlich schädlich sind, so dass es vielleicht der Mühe wert ist diese Gedanken und ihren befreienden Charakter hier nochmals auszuführen.

== Absolute Realität
Wir verwenden Begriffe wie _Realität_, _Wirklichkeit_, _Tatsachen_, _Fakten_ in der alltäglichen Kommunikation, um etwa zu sagen, etwas _entspreche nicht der Realität_, oder das und das _sei eine Tatsache_. Dies ist eine etwas nachdrücklichere Form auszudrücken, etwas sei _wahr_ oder _falsch_. Wir wollen damit zum Ausdruck bringen, dass es nicht nur unserer Meinung nach, so und so sei, sondern unbestreitbar, objektiv. Die Redeweise etwas _entspreche der Realität_ ist ein rhetorisches Mittel, um unseren Meinungen mehr Autorität zu verleihen. Entkoppeln wir aber den Begriff der Realität von seiner rhetorischen Verwendung und sprechen substantivisch über die Realität als einer unhintergehbaren Instanz die unseren Meinungen als eine Art Schiedsrichter gegenübersteht,footnote:[Ein Schiedsrichter trifft Tatsachenentscheidungen, d.h. er schafft Tatsachen.] dann sind es nicht mehr unsere Meinungen, sondern es ist die sogenannte _Realität_ selbst, die diese Autorität für sich beansprucht. Es ist die _Realität_, die alleinig dafür verantwortlich ist, dass unsere Meinungen _wahr_ oder _falsch_ sind. Das führt zu einem doppelten Standard, an dem unsere Wissensansprüche zu messen sind: zum einen gibt es unsere diversen Begründungsverfahren, die uns erlauben, ein in großen Teilen gemeinsam geteiltes Weltbild zu erstellen, auf dessen Grundlage wir unser tägliches Leben organisieren. Und zum anderen gibt es die _Realität_, die eine Entscheidung trifft, an der wir nicht beteiligt sind, und die wir noch nicht einmal kennen können. Nur Meinungen, die dem zweiten Standard genügen sind _wirklich wahr_. Dagegen können auch die besten und wissenschaftlichsten Begründungsverfahren keine _wirkliche Wahrheit_ garantieren. Bestenfalls liefern sie eine Annäherung an die Wahrheit. Wenn jemand sagt, dass es jetzt regne, und bekräftigend hinzufügt, dass dies wahr sei, dann ist diese Meinung sicher gut begründet dadurch, dass unsere Sprecherin nass wird, wenn sie aus dem Haus geht, aber ist sie _wirklich wahr_? Auch wenn wir die letzten Zweifel ausräumen können, und alle alternativen _Theorien_ verwerfen, für die _wirkliche Wahrheit_ ist alleine die _Wirklichkeit_ verantwortlich. Es ist leicht zu sehen, wie ein solcher Begriff von _Realität_ zu Frustration führen muss. Diese _Realität_ behält immer das letzte Wort. Wie sehr wir uns auch bemühen, die _Wahrheit_ zu erkennen, sie ist uns prinzipiell entzogen.

Aber macht diese Idee einer von uns und unseren Rechtfertigungsverfahren entkoppelten _Realität_ überhaupt Sinn?footnote:[Die richtige Frage wäre eigentlich "Können wir diesem Begriff einen Sinn geben"? Und die Antwort wäre "Wenn wir wollen, können wir". Also: "Wollen wir dem Begriff der absoluten und uns für immer verschlossenen Realität einen Sinn geben"?] Eine _Realität_ an der die _Wahrheit_ unserer Meinungen über sie gemessen wird, ohne dass wir selbst diese Messung durchführen. Ein Maßstab, der misst, ohne dass wir messen. Wenn wir mit einem Zollstock die Breite eines Schrankes messen, dann ist der Zollstock natürlich ein wesentliches Werkzeug in diesem Vorgang, aber wenn wir nicht gelernt hätten diesen auf eine bestimmte Weise, nämlich zur Messung einer Länge, zu benutzen, gäbe der Zollstock über die Länge keine Auskunft. Stellen wir uns eine Kultur vor, die den Gebrauch des Zollstocks nicht kennt, oder gar überhaupt keine Notwendigkeit sieht, Längen in unserem Sinn zu messen. Ohne die eingeübte Praxis des mit dem Zollstocks Messens, misst der Zollstock nicht. Und genauso verhält es sich mit dem Konzept einer von uns und unseren erlernten Verfahren, die Wahrheit einer Meinung zu beurteilen, unabhängigen _Realität_, an der sich ohne unser Zutun ihre _Wahrheit_ bemisst. Es gibt keinen Maßstab ohne die Praxis des Messens, und die sogenannte _Realität_ entscheidet nicht über die Wahrheit, ohne dass wir sie in eine Praxis des Begründens einbinden.

=== Beispiele

==== Ist die Kontinuumshypothese wahr?

==== Gibt es die Teilchen der Physik wirklich?

==== Gibt es historische Wahrheiten?

== Droht uns der Relativismus, wenn wir das Absolute aufgeben?
Ein häufiger Vorwurf gegen eine deflationistische Auffassung von Wahrheit ist der, dass ohne eine absolute Verankerung der Wahrheit in einer außersprachlichen Realität, Wahrheit nur relativ zu einem jeweils gewählten Begriffsschema sein könne. Wahr ist, was innerhalb eines Begriffsschemas als wahr anerkannt wird. Angenommen, es gäbe eine Pluralität möglicher Begriffsschemata, und es gäbe keine weiteren externen, objektiven Gründe, die die Wahrheit einer Aussage ausmachen, als die, die innerhalb eines Begriffsschemas dafür oder dagegen sprächen, und weiterhin nehmen wir an, es gäbe Aussagen, die in dem einen Begriffsschema als wahr und in dem anderen als falsch betrachtet würden, dann ist diese Aussage wahr relativ zu dem einen und falsch relativ zu dem anderen Schema, jedenfalls solange sich die Verwender der unterschiedlichen Schemata nicht durch den Austausch von weiteren Argumenten einigen können. Aber warum sollte das ausgeschlossen sein? Nun das wird in dem Begriff des Begriffsschemas vorausgesetzt: Zwischen den Kontrahenten ist eine Verständigung per Definition unmöglich. Die Begriffsschemata sind _inkommensurabel_, unvergleichbar. Es fehlt das _Tertium Comparationis_, nämlich genau diese objektive, von unseren Begriffen unabhängige Realität.

Dagegen lässt sich in zweierlei Weise argumentieren: Erstens, die Annahme inkommensurabler Begriffsschemata ist eine Schimäre. Zweitens, eine uns unzugängliche Realität vergleicht nicht und kann deshalb außerhalb eines Begriffsschemas kein Maßstab für die Wahrheit oder Falschheit einer Aussage sein. 

Donald Davidson hat in seinem Aufsatz "On the Very Idea of a Conceptual Scheme" gegen das Bild inkommensurabler Begriffsschemata vorgebracht, dass eine Interpretation einer fremden Sprachgruppe immer eine Basis geteilter Meinungen voraussetzt. Das Argument ist, wenn ich es richtig verstanden habe, relativ simpel: Wenn unsere Interpretation der Sprachgruppe zu viele falsche Meinungen unterstellt, dann ist die Interpretation nicht gelungen. Ohne gelungene Interpretation eines Begriffsschemas haben die Begriffe keine Bedeutung und es wäre nicht richtig in diesem Fall überhaupt ein Begriffsschema zu unterstellen. Davidson argumentiert damit gegen eine absolute, von unserer Interpretation unabhängige _Bedeutung_ in ähnlicher Weise wie hier gegen eine absolute _Wahrheit_ argumentiert wird. Ohne Interpretation gibt es keine Bedeutung. Ohne Rechtfertigung gibt es keine Wahrheit. Aber das nur am Rande. Wichtig für unseren Zusammenhang ist die Kritik an der Vorstellung inkommensurabler Begriffsschemata.
Ich für meinen Teil würde mir die Argumentation gegen inkommensurable Begriffsschemata noch einfacher machen: Die Unvergleichbarkeit vorgeblich unvergleichlicher Begriffsschemata wurde immer durch Vergleiche belegt.

Aber wodurch ist die Annahme solch inkommensurabler Begriffsschemata denn gerechtfertigt? Warum sollte es nicht möglich sein, eine Diskussion auch dann fortzusetzen, wenn die jeweiligen Ausgangspunkte augenscheinlich radikal verschieden sind? Ich behaupte dass unsere Begründungs- und Rechtfertigungsprozeduren sehr viel tiefer gehen als auf reine "Begriffsschemata". Auch die Einengung dessen was wir als Meinungen oder Gedanken gelten lassen wollen auf mentale oder sprachliche Entitäten vernachlässigt die breite Basis an geteilten Verhaltensmustern, sei es sprachlich oder vor-sprachlich. Meine Katze weiß dass sie morgens auf der Terrasse gefüttert wird, und erscheint deshalb in der Regel pünktlich, wenn ich aufstehe und die Terrassentür öffne, vor ihrem Fressnapf. Ich der Mensch, und sie das Tier teilen eine gemeinsame, nicht-sprachliche Kommunikation. Wir haben Verhaltensmuster, die aufeinander abgestimmt sind. Wenn solch eine Abstimmung zwischen Mensch und Tier möglich ist, wie sollte sie dann nicht möglich sein zwischen Menschen unterschiedlicher Sprachgemeinschaften oder Kulturen. Die Diskussion darüber, ob eine Meinung wahr oder falsch ist, die Argumente, die zwischen den Kombattanten ausgetauscht werden, lassen sich wenn nötig auch außersprachlich fortsetzen. Und wenn es zu keiner Einigung kommt, so gibt es doch zumindest die Verständigung hinsichtlich der grundlegendsten menschlichen Bedürfnisse.
Auch wenn wir zugestehen, dass es sehr grundsätzliche Meinungsunterschiede geben mag, so rechtfertigt doch nichts die Annahme, dass diese Meinungsunterschiede inkommensurabel also schlicht hinsichtlich ihrer Wahrheit nicht miteinander vergleichbar sein sollen. Es sind wir, die Menschen, die vergleichen. Es braucht keinen absoluten Maßstab, der diese Meinungen vergleicht und diese wahr oder falsch macht. Einen solchen Maßstab, der misst, ohne dass es jemanden gibt, der den Maßstab zu lesen und anzuwenden weiß, kann es nicht geben.
Man sagt man dürfe nicht Äpfel und Birnen vergleichen. Warum nicht? Das hängt davon ab. Natürlich kann ich nicht sagen, diese Birne sei der saftigere Apfel, aber ich kann problemlos die Farbe des Apfels mit der Farbe der Birne vergleichen. Ob zwei Dinge vergleichbar sind oder nicht, hängt davon ab, ob ich sie vergleichen will oder nicht.

== Philosophische Wahrheitstheorien

=== Kohärenztheorie

=== Pragmatistische Theorie der Wahrheit

=== Horizontale und vertikale Begründungen
Philosophische Theorien der Wahrheit, egal welchen Typs, zeichnen sich dadurch aus, dass sie zusätzlich zu den gewöhnlichen, argumentativen Rechtfertigungen einzelner Behauptungen eine Natur der Wahrheit postulieren, irgendetwas was dafür verantwortlich ist, dass etwas wirklich wahr ist oder nicht, egal zu welchem Ergebnis wir mit unseren argumentativen Verfahren wir kommen. Ich will diese außer-argumentativen Ideen, wodurch etwas wahr, gut oder schön wird, vertikale Begründungen nennen. Unsere Meinungen über die Welt müssen sich einer absoluten, nicht vom Menschen abhängigen Natur der Wahrheit beugen. Diese Natur steht sozusagen im "rechten Winkel" zu unseren in der menschlichen Gesellschaft anerkannten Begründungen. Die philosophische Wahrheit und die argumentative Wahrheit sind unabhängige Vektoren. Die philosophische  Wahrheit zeigt auf etwas "außerhalb" unseres Netzes sozial argumentativer, gut begründeter Meinungen, die unsere Kriterien gut gerechtfertigten Wissens erfüllen. Sei es die Welt an sich, sei es ein abstrakter Begriff der Kohärenz, sei es die absolute Gültigkeit des Nützlichen für eine bessere Zukunft der Menschheit.
Wenn man diese absolute, unhintergehbare Natur der Wahrheit fallen lässt, und die letzte und einzige Begründung unseres vorgeblichen Wissens bei uns Menschen und ihrer Praxis belässt, die in ihre Argumentationsmuster, den sprachlichen und außersprachlichen Kontext miteinbeziehen, dann kann man durchaus sagen, dass ein Gedanke wahr ist, wenn er mit der Realität übereinstimmt, oder wenn er zu unseren anderen gut begründeten Gedanken passt, oder dass wir in der Regel denjenigen Meinungen den Vorzug geben, die uns in unserer Lebenspraxis helfen und idealerweise zu einem größeren Glück der größeren Zahl führen. Wir müssen also aus den aufgeblasenen, philosophischen Theorien die Luft raus lassen, indem wir sie nicht als vertikale Beschreibungen einer außer-pragmatischen Natur der Wahrheit betrachten, sondern als bloß weitere Kommentare zu unserem System von Meinungen, die aber selbst jederzeit hinterfragbar und einer Begründung erforderlich sein können. Diese Kommentare sind "horizontal", sie gehören zu unserem Netz von Meinungen einfach dazu. 

== Absolute Autoritäten

=== Das jüngste Gericht

=== Menschenrechte

=== Sinneseindrücke

=== Die _Natur_

=== Beweise

== Ausblick

=== Vom Fortsetzen einer (Spiel-) Regel